apiVersion: v1
kind: Service
metadata:
  name: authentication-internal
  namespace: yuuvis
  labels:
    app: yuuvis
    name: authentication-internal
spec:
  ports:
    - name: '80'
      protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    name: authentication
  type: ClusterIP
