imageCredentials:
  dockeryuuvisorg:
  # Credentials received from Optimal Systems
    registry: docker.yuuvis.org
    username: 
    password: 
redis:
  master:
    persistence:
      storageClass: managed-premium
      
postgresql:
  auth:
  # Choose a new password. 
  # This password is not needed in the eakte installation
    postgresPassword: changeme
  primary:  
    persistence:
      storageClass: managed-premium
eakte:
  db:
    # user will be created in the postgresql database
    # choose a new password
    user: eakte
    password: changeme
  api: 
    instances: 1
  client:
    instances: 1
  feedback:
    instances: 1
    credentials:
      # Credentials received from Optimal Systems
      accessKeyId: ""
      secretAccessKey: ""
  webhook:
    instances: 1
  filePlanImporter:
    instances: 1

yuuvis:
  namespace: yuuvis
  amqp:
  # Credentials from the Yuuvis Infrastructure Installation
    url: rabbitmq.infrastructure:5672
    username: rodger
    password: changeme
  # Credentials from an user with the role YUUVIS_SYSTEM_INTEGRATOR
  systemAdmin:
    tenant: changeme
    username: changeme
    password: changeme