apiVersion: v2
name: eakte
description: A Helm chart for the E-Akte Kubernetes installation
type: application
version: 1.3.4
appVersion: "1.3.2"
dependencies:
- name: redis
  version: ^16.12.2
  repository: https://charts.bitnami.com/bitnami
- name: nginx
  version: ^13.2.2
  repository: https://charts.bitnami.com/bitnami
- name: postgresql
  version: ^11.6.7
  repository: https://charts.bitnami.com/bitnami
