apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.eakte.labels.app}}
    name: eakte-feedback
  name: eakte-feedback
spec:
  replicas: {{.Values.eakte.feedback.instances}}
  selector:
    matchLabels:
      name: eakte-feedback
  template:
    metadata:
      labels:
        name: eakte-feedback
    spec:
      containers:
      - image: "{{.Values.eakte.feedback.dockerRegistry}}:{{ default .Chart.AppVersion .Values.eakte.feedback.tag }}"
        imagePullPolicy: {{ .Values.eakte.image.imagePullPolicy }}
        name: eakte-feedback
        env:
          - name: FASTIFY_ADDRESS
            value: 0.0.0.0
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: eakte-feedback-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: eakte-feedback-secret
                key: AWS_SECRET_ACCESS_KEY
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 128Mi
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 30
      imagePullSecrets:
      - name: {{.Values.eakte.image.imagePullSecret }}
      tolerations: {{ .Values.eakte.tolerations | toYaml | nindent 8 }}
      restartPolicy: Always

