apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.eakte.labels.app}}
    yuuvis: "true"
    name: eakte-feedback
  name: eakte-feedback
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    name: eakte-feedback
  type: ClusterIP