apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.eakte.labels.app}}
    name: eakte-fileplan-importer
  name: eakte-fileplan-importer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: eakte-fileplan-importer
  type: ClusterIP