apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.eakte.labels.app}}
    name: eakte-client
  name: eakte-client
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: eakte-client
  type: ClusterIP