apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.eakte.labels.app}}
    name: eakte-admin
    yuuvis: "true"
  name: eakte-admin
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 3000
  selector:
    name: eakte-admin
  type: ClusterIP
