apiVersion: v1
kind: Secret
metadata:
  name: eakte-feedback-secret
stringData:
  AWS_ACCESS_KEY_ID: {{.Values.eakte.feedback.credentials.awsAccessKeyId}}
  AWS_SECRET_ACCESS_KEY: {{.Values.eakte.feedback.credentials.awsSecretAccessKey}}