apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.eakte.labels.app}}
    name: eakte-webhook
  name: eakte-webhook
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
  selector:
    name: eakte-webhook
  type: ClusterIP
