apiVersion: v1
kind: Secret
metadata:
  name: eakte-setup-secret
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
stringData:
  YUUVIS_ADMIN_TENANT: "{{.Values.yuuvis.systemAdmin.tenant}}"
  YUUVIS_ADMIN_USERNAME: "{{.Values.yuuvis.systemAdmin.username}}"
  YUUVIS_ADMIN_PASSWORD: "{{.Values.yuuvis.systemAdmin.password}}"
  AMQP_URL: "{{.Values.yuuvis.amqp.url}}"
  AMQP_USERNAME: "{{.Values.yuuvis.amqp.username}}"
  AMQP_PASSWORD: "{{.Values.yuuvis.amqp.password}}"