apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb
data:
  create_eakte_dbs.sql: |
    CREATE DATABASE eakte;
    CREATE USER {{.Values.eakte.db.user}} WITH ENCRYPTED PASSWORD '{{.Values.eakte.db.password}}';
    GRANT ALL PRIVILEGES ON DATABASE eakte TO {{.Values.eakte.db.user}};