{{ if .Values.yuuvis.selfSignedCerts.copyToEAkte }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: eakte
  name: copy-selfsigned-cert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: eakte
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: copy-selfsigned-cert
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: copy-selfsigned-cert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: copy-selfsigned-cert
subjects:
- kind: ServiceAccount
  name: copy-selfsigned-cert
  namespace: {{ .Release.Namespace }}
{{ end }}